#ifndef _HAL_LED_H
#define _HAL_LED_H

#define LED1_PORT GPIOA
#define LED1_PIN GPIO_Pin_1

#define BUZ_PORT GPIOB
#define BUZ_PIN GPIO_Pin_0

#define LEF_EFFECT_END 0XFFFE
#define LEF_EFFECT_AGN 0XFFFF

typedef enum {
  LED1,  // LED
  BUZ,   // BUZZER
  LED_SUM
} LED_TYPEDEF;

typedef enum {
  LED_DARK,
  LED_LIGHT,
  LED_LIGHT_100MS,
  LED_BLINK1,
  LED_BLINK2,
  LED_BLINK3,
  LED_BLINK4,
} LED_EFFECT_TYPEDEF;
#endif